{
 "title": "qBittorrent",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Time Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dl_info_data_alltime", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "All Time Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up_info_data_alltime", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Session Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dl_info_data" }
   ]
  },
  {
   "title": "Session Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up_info_data" }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "dl_info_speed" }
   ]
  },
  {
   "title": "Global Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "up_info_speed" }
   ]
  },
  {
   "title": "Download/Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "dl_info_speed{}", "legendFormat": "{{host}} - Download" },
    { "expr": "up_info_speed{}", "legendFormat": "{{host}} - Upload" }
   ]
  },
  {
   "title": "Download/Upload per session",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "dl_info_data", "legendFormat": "{{host}} - Download" },
    { "expr": "up_info_data", "legendFormat": "{{host}} - Upload" }
   ]
  },
  {
   "title": "Download/Upload all-time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "dl_info_data_alltime", "legendFormat": "{{host}} - Download" },
    { "expr": "up_info_data_alltime", "legendFormat": "{{host}} - Upload" }
   ]
  }
 ]
}